### ISSUE TITLE
Please provide SQLite database version

### ISSUE THREAD

**Issue by performance** [theimowski/SuaveMusicStore#1]
This makes it significantly easier to reproduce the project on all platforms.

**Comment by theimowski** [comment]
How about implementing an in-memory store? It could be a solution for those struggling with the mssql + type provider to get working.

**Comment by theimowski** [comment]
I've started some work on an in-memory Db [here](https://github.com/theimowski/SuaveMusicStore/tree/inmemory-db) - would you like to contribute to make it work?

**Comment by performance** [comment]
It works on Xamarin Studio on OSX. :)  But the submit order throws some
thing up..  could you please try to place an order with one album?I will
also look into that.

**Comment by lefthandedgoat** [comment]
I didn't realize that @theimowski  had already started on an in memory db.  I have done some work on that too here:

https://github.com/lefthandedgoat/SuaveMusicStore/commits/master

It doesnt do saving or updating or anything, but lets me load the site on OSX.

**Comment by theimowski** [comment]
My in-memory version still requires a bunch of stuff to correct - I'll give it a try soon

**Comment by lefthandedgoat** [comment]
I am also working on a postgres version:

https://github.com/lefthandedgoat/SuaveMusicStore/commits/postgres

**Comment by theimowski** [comment]
That's great - when you feel it's ready could you please send PR? I think others could benefit from that as well

**Comment by lefthandedgoat** [comment]
@theimowski I have working postgres support.  I used the Npqsql Implimentation, which is like ADO.net instead of a type provider.  I chose this because the postgres sql provider says it is still alpha and not ready for production use.  I wanted to learn postgres so I can create a product so this was the safest choice.

I am not sure how it can co-exist with the normal db.fs so I have it all commented out.

It could maybe use some more love?

SQL script
https://github.com/lefthandedgoat/SuaveMusicStore/blob/postgres/postgres_create.sql

DB
https://github.com/lefthandedgoat/SuaveMusicStore/blob/postgres/Db_Postgres.fs

Think about how these can co-exist, if they can, and if they can't it can just live as another branch.

**Comment by theimowski** [comment]
How about that: https://github.com/theimowski/SuaveMusicStore/commit/c2920b467084f2288a7b0aaa926a26c79256fff0 ? 
I used a module alias in two files to determine whether to use MsSql or Postgres Db variation.
If for one the MsSql version does not compile because of the type provider - they could simply exclude it from project or comment

**Comment by lefthandedgoat** [comment]
looks great, I will pull that in and test some!

**Comment by theimowski** [comment]
Postgres is now used in recently published version. The contributing guideline for the tutorial wasn't clear - now I've written the guidelines [here](https://github.com/theimowski/SuaveMusicStore/blob/contents/CONTRIBUTING.md)

**Comment by performance** [comment]
Hey Tomasz,
 Sorry I couldn't respond sooner.    Thanks for addressing this issue.
Cheers
Ram
